import pygame


all_events_list = ['END_TURN',
                  'SWITCH_BORD_TO_MAP',
                  'DIRECT_FLIGHT',
                  'DISCOVER_CURE',
                  'SHARE_KNOWLEDGE',
                  'CURE_BLUE',
                  'CURE_YELLOW',
                  'CURE_BLACK',
                  'CURE_RED',
                  'BUILED_RESEARCH_STATION',
                  'SWITCH_BORD_TO_CARDS',
                  'CLICK_ON_CARD',
                  'CLICK_ON_CITY',
                  'MOVE_TO_CITY',
                  'PLAYER_1',
                  'PLAYER_2',
                  'PLAYER_3',
                  'PLAYER_4',
                  'USE_EVENT_CARD',
                  'ONE_QUIET_NIGHT',
                  'RESILIENT_POPULATION',
                  'FORECAST',
                  'GOVERNMENT_GRANT',
                  'AIRLIFT',
                  'APPLY_FORECAST',
                  'APPLY_RESILIENT_POPULATION',
                  'DISPLAY_INFACTION_DISCARD_CARD',
                  'DISPLAY_PLAYER_DISCARD_CARD',
                  'DISPLAY_CONTINGENCY_PLANNER_DISCARD_CARD',
                  'CONTINGENCY_PLANNER_TAKE_DISCARD_CARD',
                  'END_GAME_HAND_LIMIT',
                  'APPLY_HAND_LIMIT',
                  'APPLY_END_GAME_HAND_LIMIT',
                  'INFACTION_PHASE',
                  'ONE_EPIDEMIC',
                  'EPIDEMIC',
                  'PLAYERS_MAY_PLAY_EVENT',
                  'NEXT_PLAYER',
                  'NEW_GAME',
                  'SWITCH_BORD_TO_COSTUM_GAME',
                  'SWITCH_BORD_TO_SETTING',
                  'SWITCH_BORD_TO_MAIN_MANUE',
                  'ADD_EPIDEMIC_CARD',
                  'SUBTRACT_EPIDEMIC_CARD',
                  'SUBTRACT_PLAYER', 
                  'ADD_PLAYER',
                  'SWITCH_BORD_TO_COLOR_SETTING']

all_events = {event_name : pygame.USEREVENT + i for i, event_name in enumerate(all_events_list)}

bottons_events = {'switch_bord_to_map' : all_events['SWITCH_BORD_TO_MAP'],
                  'direct_flight' : all_events['DIRECT_FLIGHT'],
                  'discover_cure' : all_events['DISCOVER_CURE'],
                  'share_knowledge' : all_events['SHARE_KNOWLEDGE'],
                  'cure_blue' : all_events['CURE_BLUE'],
                  'cure_yellow' : all_events['CURE_YELLOW'],
                  'cure_black' : all_events['CURE_BLACK'],
                  'cure_red' : all_events['CURE_RED'],
                  'builed_research_station' : all_events['BUILED_RESEARCH_STATION'],
                  'switch_bord_to_cards' : all_events['SWITCH_BORD_TO_CARDS'],
                  'player 1' : all_events['PLAYER_1'],
                  'player 2' : all_events['PLAYER_2'],
                  'player 3' : all_events['PLAYER_3'],
                  'player 4' : all_events['PLAYER_4'],
                  'use_event_card' : all_events['USE_EVENT_CARD'],
                  'apply_forcast' : all_events['APPLY_FORECAST'],
                  'apply_resilient_population' : all_events['APPLY_RESILIENT_POPULATION'],
                  'contingency_planner_take_discard_card' : all_events['CONTINGENCY_PLANNER_TAKE_DISCARD_CARD'],
                  'apply_hand_limit' : all_events['APPLY_HAND_LIMIT'],
                  'apply_end_game_hand_limit' : all_events['APPLY_END_GAME_HAND_LIMIT'],
                  'epidemic' : all_events['EPIDEMIC'],
                  'new_game' :all_events['NEW_GAME'],
                  'switch_bord_to_costum_game' : all_events['SWITCH_BORD_TO_COSTUM_GAME'],
                  'switch_bord_to_setting': all_events['SWITCH_BORD_TO_SETTING'],
                  'switch_bord_to_main_manue' : all_events['SWITCH_BORD_TO_MAIN_MANUE'],
                  'quiet' : pygame.QUIT,
                  'add_epidemic_card' : all_events['ADD_EPIDEMIC_CARD'], 
                  'subtract_epidemic_card' : all_events['SUBTRACT_EPIDEMIC_CARD'],
                   'subtract_player' : all_events[ 'SUBTRACT_PLAYER'], 
                   'add_player' : all_events['ADD_PLAYER'],
                   'switch_bord_to_color_setting' : all_events['SWITCH_BORD_TO_COLOR_SETTING']}





events_cards_events = {'one quiet night' : all_events['ONE_QUIET_NIGHT'],
                       'resilient population' : all_events['RESILIENT_POPULATION'],
                       'forecast' : all_events['FORECAST'],
                       'airlift' : all_events['AIRLIFT'],
                       'government grant' : all_events['GOVERNMENT_GRANT']}
